config/routes.rb
Rails.application.routes.draw do
  get 'assessments/autocomplete_program_description'
  get 'assessments/autocomplete_period_description'
  get 'assessments/autocomplete_department_description'

  resources :entries
  resources :assessmenttypes
  resources :assessments
  resources :periods
  resources :programs
  resources :departments
  resources :colleges
  devise_for :users
  get 'login/index'
  get 'home/index'

  authenticated :user do
    root to: 'assessments#index', as: "authenticated_root"
  end
  root to: 'login#index'

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :program
  belongs_to :period
  belongs_to :user
  belongs_to :department
  has_many :entries
  accepts_nested_attributes_for :entries
  after_create :create_new_entries
  # Program getter
  def program_description
    program.try(:description)
  end

  # Program setter
  def program_description=(description)
    self.program = Program.find_or_create_by(description: description) if description.present?
  end

  # Period getter
  def period_description
    period.try(:description)
  end

  # Period setter
  def period_description=(description)
    self.period = Period.find_or_create_by(description: description) if description.present?
  end

  # Department getter
  def department_description
    department.try(:description)
  end

  # Department setter
  def department_description=(description)
    self.department = Department.find_or_create_by(description: description) if description.present?
  end

  private

    def create_new_entries
      Assessmenttype.all.each do | atype |
        entry = Entry.new
        entry.assessment_id = self.id
        entry.assessmenttype_id = atype.id
        entry.save!
      end
    end

end

app/models/assessmenttype.rb
class Assessmenttype < ActiveRecord::Base
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]
  autocomplete :program, :description, :full => true
  autocomplete :period, :description, :full => true
  autocomplete :department, :description, :full => true
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.where(user_id: current_user)
    if params[:search]
      @program = Program.description_like("%#{params[:search]}%").order('description')
    else
    end

    if params[:search]
      @period = Period.description_like("%#{params[:search]}%").order('description')
    else
    end

    if params[:search]
      @department = Department.description_like("%#{params[:search]}%").order('description')
    else
    end
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessments = Assessment.find(params[:id])
  end

  # GET /assessments/new
  def new
    @assessment = current_user.assessments.build
  end

  # GET /assessments/1/edit
  def edit
    @assessment = Assessment.find params[:id]
    unless current_user == @assessment.user
      redirect_to(@assessment, notice: "Access denied.") and return
    end
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = current_user.assessments.build(assessment_params)

    respond_to do |format|
      if @assessment.save
        flash[:success] = 'Assessment was successfully created.'
        format.html { redirect_to edit_assessment_path(@assessment), notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        flash[:success] = 'Assessment was successfully updated.'
        format.html { redirect_to edit_assessment_path(@assessment), notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        flash[:danger] = 'There was a problem updating the Assessment.'
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    unless current_user == @assessment.user
      redirect_to(assessments_url, notice: "You can't destroy this assessment because you didn't create it.") and return
    else
      @assessment.destroy
      respond_to do |format|
        flash[:success] = 'Assessment was successfully destroyed.'
        format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.' }
        format.json { head :no_content }
        end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assessment
    @assessment = Assessment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assessment_params
    params.require(:assessment).permit(:program_id, :period_id, :user_id, :completed, :department_id, :program_description, :period_description, :department_description, :entries_attributes => [:id, :initial_rating, :initial_comment, :final_rating, :final_comment])
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<h1> Academic Program Assessment Maturity Rubric </h1>
<%= form_for(@assessment) do |f| %>
    <% if @assessment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

          <ul>
            <% @assessment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-inputs">
      <%= f.label "Department" %><br>
      <%= f.autocomplete_field :department_description, assessments_autocomplete_department_description_path %>
    </div>
    <div class="form-inputs">
      <%= f.label "Degree" %><br>
      <%= f.autocomplete_field :program_description, assessments_autocomplete_program_description_path %>
    </div>
    <div class="form-inputs">
      <%= f.label "Semester" %><br>
      <%= f.autocomplete_field :period_description, assessments_autocomplete_period_description_path %>
    </div>
    <div class="field">
      <%= f.label "User" %><br />
      <%= @users = User.all
          collection_select(:assessment,:user_id, @users,:id,:email) %>
    </div>
    </br>
    <div class="field">
      <%= f.label :completed %><br>
      <%= f.check_box :completed %>
    </div>


    <% @assessment.entries.each do |entry| %>
        <%= f.fields_for :entries, entry do |ef| %>
            <h3> <%= Assessmenttype.find(entry.assessmenttype_id).attype %> </h3>
            <div class="field">
              <%= ef.label "Initial Rating (0-3)" %><br>
              <%= ef.select :initial_rating, (0..3) %>
            </div>
            <div class="field">
              <%= ef.label "Initial Comment" %><br>
              <%= ef.text_field :initial_comment %>
            </div>
            <div class="field">
              <%= ef.label "Final Rating (0-3)" %><br>
              <%= ef.select :final_rating, (0..3) %>
            </div>
            <div class="field">
              <%= ef.label "Final Comment" %><br>
              <%= ef.text_field :final_comment %>
            </div>
        <% end %>
    <% end %>
    </br>
    <div class="actions">
      <%= f.submit "Update Assessment", :class => "button"%>
    </div>
    </br>
<% end %>

app/views/assessments/edit.html.erb
<%= render 'form' %>

app/views/assessments/index.html.erb
<h1>Listing Assessments</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Degree</th>
      <th>Semester</th>
      <th>User</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= assessment.department.description %></td>
        <td><%= assessment.program.description %></td>
        <td><%= assessment.period.description %></td>
        <td><%= assessment.user.email %></td>
        <td><%= assessment.completed %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<%= link_to 'New Assessment', new_assessment_path %>
<br/>
<br/>

app/views/assessments/new.html.erb
<h1>New Assessment</h1>

<%= render 'form' %>

<%= link_to 'Back', assessments_path %>

app/views/assessments/show.html.haml
!!!
%html
  = render 'form'