config/routes.rb
Rails.application.routes.draw do
  get 'assessments/autocomplete_program_description'
  get 'assessments/autocomplete_period_description'
  get 'assessments/autocomplete_department_description'

  resources :entries
  resources :assessmenttypes
  resources :assessments
  resources :periods
  resources :programs
  resources :departments
  resources :colleges
  devise_for :users
  get 'login/index'
  get 'home/index'

  authenticated :user do
    root to: 'assessments#index', as: "authenticated_root"
  end
  root to: 'login#index'

end

app/controllers/assessmenttypes_controller.rb
class AssessmenttypesController < ApplicationController
  before_action :set_assessmenttype, only: [:show, :edit, :update, :destroy]

  # GET /assessmenttypes
  # GET /assessmenttypes.json
  def index
    @assessmenttypes = Assessmenttype.all
  end

  # GET /assessmenttypes/1
  # GET /assessmenttypes/1.json
  def show
  end

  # GET /assessmenttypes/new
  def new
    @assessmenttype = Assessmenttype.new
  end

  # GET /assessmenttypes/1/edit
  def edit
  end

  # POST /assessmenttypes
  # POST /assessmenttypes.json
  def create
    @assessmenttype = Assessmenttype.new(assessmenttype_params)

    respond_to do |format|
      if @assessmenttype.save
        format.html { redirect_to @assessmenttype, notice: 'Assessmenttype was successfully created.' }
        format.json { render :show, status: :created, location: @assessmenttype }
      else
        format.html { render :new }
        format.json { render json: @assessmenttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessmenttypes/1
  # PATCH/PUT /assessmenttypes/1.json
  def update
    respond_to do |format|
      if @assessmenttype.update(assessmenttype_params)
        format.html { redirect_to @assessmenttype, notice: 'Assessmenttype was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessmenttype }
      else
        format.html { render :edit }
        format.json { render json: @assessmenttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessmenttypes/1
  # DELETE /assessmenttypes/1.json
  def destroy
    @assessmenttype.destroy
    respond_to do |format|
      format.html { redirect_to assessmenttypes_url, notice: 'Assessmenttype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessmenttype
      @assessmenttype = Assessmenttype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessmenttype_params
      params.require(:assessmenttype).permit(:attype, :description)
    end
end

app/helpers/assessmenttypes_helper.rb
module AssessmenttypesHelper
end

app/views/assessmenttypes/_form.html.erb
<%= form_for(@assessmenttype) do |f| %>
  <% if @assessmenttype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessmenttype.errors.count, "error") %> prohibited this assessmenttype from being saved:</h2>

      <ul>
      <% @assessmenttype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attype %><br>
    <%= f.text_field :attype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assessmenttypes/edit.html.erb
<h1>Editing Assessmenttype</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessmenttype %> |
<%= link_to 'Back', assessmenttypes_path %>

app/views/assessmenttypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assessmenttypes</h1>

<table>
  <thead>
    <tr>
      <th>Attype</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assessmenttypes.each do |assessmenttype| %>
      <tr>
        <td><%= assessmenttype.attype %></td>
        <td><%= assessmenttype.description %></td>
        <td><%= link_to 'Show', assessmenttype %></td>
        <td><%= link_to 'Edit', edit_assessmenttype_path(assessmenttype) %></td>
        <td><%= link_to 'Destroy', assessmenttype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assessmenttype', new_assessmenttype_path %>

app/views/assessmenttypes/new.html.erb
<h1>New Assessmenttype</h1>

<%= render 'form' %>

<%= link_to 'Back', assessmenttypes_path %>

app/views/assessmenttypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attype:</strong>
  <%= @assessmenttype.attype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assessmenttype.description %>
</p>

<%= link_to 'Edit', edit_assessmenttype_path(@assessmenttype) %> |
<%= link_to 'Back', assessmenttypes_path %>