config/routes.rb
Rails.application.routes.draw do
  get 'assessments/autocomplete_program_description'
  get 'assessments/autocomplete_period_description'
  get 'assessments/autocomplete_department_description'

  resources :entries
  resources :assessmenttypes
  resources :assessments
  resources :periods
  resources :programs
  resources :departments
  resources :colleges
  devise_for :users
  get 'login/index'
  get 'home/index'

  authenticated :user do
    root to: 'assessments#index', as: "authenticated_root"
  end
  root to: 'login#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :department
  has_and_belongs_to_many :users
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:department_id, :description)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.department %></td>
        <td><%= program.description %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @program.department %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>